sudo: required

language: go

services:
  - docker

env:
  - TARGET_CONTAINER_ID=container-php-emacs

before_script:
  - docker build -t git-http-transfer-build .

script:
  - docker run --rm -v $PWD:/go/src/github.com/vvatanabe/go-git-http-transfer git-http-transfer-build bash -c "go test -cover -v ./githttptransfer"