sudo: required

language: go

services:
  - docker

before_script:
  - go get github.com/mattn/goveralls
  - docker build -t go-git-http-xfer .

script:
  - docker run --rm -v $PWD:/go/src/github.com/nulab/go-git-http-xfer go-git-http-xfer bash -c "gotestcover -v -covermode=count -coverprofile=coverage.out ./..."
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service travis-ci