sudo: required

language: go

services:
  - docker

before_script:
  - go get github.com/mattn/goveralls
  - docker build -t git-http-transfer-build .

script:
  - docker run --rm -v $PWD:/go/src/github.com/vvatanabe/go-git-http-transfer git-http-transfer-build bash -c "go test -v -covermode=count -coverprofile=coverage.out ./githttptransfer"
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service travis-ci